// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Account struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	CreateTime time.Time `json:"create_time"`
}

type AccountAccessRule struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	AccountID int64 `json:"account_id"`
	Role      int32 `json:"role"`
}

type Record struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Type               int32     `json:"type"`
	Date               time.Time `json:"date"`
	Amount             string    `json:"amount"`
	AccountID          int64     `json:"account_id"`
	CreateUserID       int64     `json:"create_user_id"`
	LastModifiedUserID int64     `json:"last_modified_user_id"`
	CreateTime         time.Time `json:"create_time"`
}

type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreateTime     time.Time `json:"create_time"`
}
